### ISSUE TITLE
Doesn't run on .NET8

### ISSUE THREAD

**Issue by AndreasDecke** [aniqoff-DEV/DemoEmployeeManagementSystem#11]
Hello,

Unfortunately I can't get the app to run under .NET 8! (I changed all projects to .NET8. A NUGET update was then started for all projects.) When I log in I get the following error message:

`crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: TypeError: Failed to fetch
System.Net.Http.HttpRequestException: TypeError: Failed to fetch
 ---> TypeError: Failed to fetch

at System.Net.Http.BrowserHttpInterop.<CancelationHelper>d__13`1[[System.Runtime.InteropServices.JavaScript.JSObject, System.Runtime.InteropServices.JavaScript, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
at System.Net.Http.BrowserHttpHandler.CallFetch(HttpRequestMessage request, CancellationToken cancellationToken, Nullable`1 allowAutoRedirect)
at System.Net.Http.BrowserHttpHandler.<SendAsync>g__Impl|53_0(HttpRequestMessage request, CancellationToken cancellationToken, Nullable`1 allowAutoRedirect)
at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
at ClientLibrary.Helpers.CustomHtppHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in E:\Repos\DemoEmployeeManagementSystem\ClientLibrary\Helpers\CustomHtppHandler.cs:line 29
at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
at ClientLibrary.Services.Implementations.UserAccountServices.SignInAsync(Login user) in E:\Repos\DemoEmployeeManagementSystem\ClientLibrary\Services\Implementations\UserAccountServices.cs:line 31
at Client.Pages.AccountPages.LoginPage.HandleLogin() in E:\Repos\DemoEmployeeManagementSystem\Client\Pages\AccountPages\LoginPage.razor:line 75
at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
`
It would be nice if the code also ran under .NET 8 
Thank you for the effort

**Comment by aniqoff-DEV** [comment]
Hello!
The working draft is completed on net7 like all packages! I read that you updated it, but according to the error output, there is a error, as I think, in the authorization tokens.

**Comment by aniqoff-DEV** [comment]
You have indicated the lines where the error occurred, look where and what exactly.
